### ISSUE TITLE
请问签退时出现 载入账户时出现异常 是因为接口更新了吗，是否有解决办法

### ISSUE THREAD

**Issue by RenOrimaki** [TiyaAnlite/xybAutoSign#9]
START RequestId: 3d99e087-f11e-4333-acd3-65dc3665579c2022-07-05 14:56:00,316 - XybAccount - INFO: 正在使用账号密码登录
Starting new HTTPS connection (1): xcx.xybsyw.com:443
2022-07-05 14:56:00,383 - XybSign - ERROR: 载入账户时出现异常
2022-07-05 14:56:00,383 - XybSign - ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/python3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/var/lang/python3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/var/lang/python3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/var/lang/python3/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/user/xyb.py", line 402, in __init__
    self._accounts.append(XybAccount(**acc))
  File "/var/user/xyb.py", line 47, in __init__
    self.login()
  File "/var/user/xyb.py", line 62, in login
    self.login_phone()
  File "/var/user/xyb.py", line 95, in login_phone
    resp = self.session.post(url=XybSign.URL_LOGIN_PHONE, data=data).json()
  File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/lang/python3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-07-05 14:56:00,384 - XybSign - INFO: 已载入 0 个账号
2022-07-05 14:56:00,384 - XybSign - INFO: 开始批量签退 0 个账户
2022-07-05 14:56:00,384 - XybSign - INFO: 任务结束，0(成功) / 0(失败)
2022-07-05 14:56:00,384 - XybSign - INFO: Webhooks: 0 || 0(完成) / 0(失败)
Response RequestId: 3d99e087-f11e-4333-acd3-65dc3665579c RetMsg: nullEND RequestId: 3d99e087-f11e-4333-acd3-65dc3665579cReport RequestId: 3d99e087-f11e-4333-acd3-65dc3665579c Duration: 71ms Memory: 128MB MemUsage: 18.47MB

**Comment by RenOrimaki** [comment]
有正常上传健康码，且在下午五点左右可以正常签退，六点左右输出日志如上，不能正常签退。

**Comment by TiyaAnlite** [comment]
这种一般来说是网络出问题，如果是近期能用突然不能用可以过一段时间再重试下看看，可能是那边服务器的问题

**Comment by RenOrimaki** [comment]
> 一般来说是网络出问题了，如果是近期能用过的问题再重试下看看，可能是这个服务器的问题

好的，非常感谢，明天我再试一下。
